version: "3.8"

services:
  dev-api:
    build: .
    container_name: dev-api
    hostname: dev-api
    restart: unless-stopped
    cap_add:
      - SYS_TIME
    ports:
      - "127.0.0.1:4180:8000"
    networks:
      - api_shared_network
    env_file:
      - .env

networks:
  api_shared_network:
    external: true